# Generated by Django 3.2.8 on 2021-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ratingstart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_en_us',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='description_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='title_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movieshots',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
