# Generated by Django 3.2.8 on 2021-11-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211106_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='categorymodel',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_en_us',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country_en_us',
            new_name='country_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='tagline_en_us',
            new_name='tagline_en',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title_en_us',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='movieshots',
            old_name='description_en_us',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='movieshots',
            old_name='title_en_us',
            new_name='title_en',
        ),
    ]
